#!/usr/bin/env python3
"""
Convert the paper's LaTeX source into a structured intermediate representation
that the DOCX builder can render with the ETFG-2025 template styles.

The paper uses a deliberately small LaTeX subset, so this is a targeted
converter rather than a general one. It is not a rewrite: the narrative text is
carried across verbatim, with inline markup mapped onto Word runs.

Output: docxbuild/paper_ir.json
"""
from __future__ import annotations

import json
import re
from pathlib import Path

SRC = Path("../repo/paper/main.tex")

# ---------------------------------------------------------------- labels ----
LABELS = {
    "tab:positioning": "Table I", "tab:policy": "Table II", "tab:corpus": "Table III",
    "tab:headline": "Table IV", "tab:perrule": "Table V", "tab:adv": "Table VI",
    "fig:arch": "Fig. 1", "fig:accuracy": "Fig. 2", "fig:confusion": "Fig. 3",
    "sec:results": "Section V", "sec:ablation": "Section VI-C", "sec:threat": "Section III",
    "sec:limits": "Section VII", "sec:related": "Section II", "sec:method": "Section IV",
    "sec:corpus": "Section IV-E",
}

# Unicode replacements applied inside math and text
SYM = {
    r"\ge": "≥", r"\le": "≤", r"\in": "∈", r"\wedge": "∧", r"\rightarrow": "→",
    r"\theta": "θ", r"\alpha": "α", r"\beta": "β", r"\times": "×", r"\pm": "±",
    r"\approx": "≈", r"\cdot": "·", r"\{": "{", r"\}": "}",
    r"\text{DENY}": "DENY", r"\text{ACCEPT}": "ACCEPT", r"\text{FLAG}": "FLAG",
    r"\text{otherwise}": "otherwise", r"\text{strong}": "strong",
}


def strip_comments(t: str) -> str:
    out = []
    for line in t.splitlines():
        if line.lstrip().startswith("%"):
            continue
        out.append(line)
    return "\n".join(out)


def load_macros(path):
    """Numeric macros generated by make_macros.py."""
    src = Path(path).read_text()
    out = {}
    for name, val in re.findall(r"\\newcommand\{\\([A-Za-z]+)\}\{((?:[^{}]|\{[^{}]*\})*)\}", src):
        out[name] = val
    return out


def expand_macros(tex: str, macros):
    """Replace \\MacroName with its value, longest name first."""
    for name in sorted(macros, key=len, reverse=True):
        tex = re.sub(r"\\" + name + r"(?![A-Za-z])", macros[name].replace("\\", "\\\\"), tex)
    return tex


def build_citation_map(tex: str):
    """Map bibitem key -> [n] in the order the bibliography lists them."""
    bib = re.search(r"\\begin\{thebibliography\}\{99\}(.*?)\\end\{thebibliography\}", tex, re.S).group(1)
    keys = re.findall(r"\\bibitem\{([^}]+)\}", bib)
    return {k: i + 1 for i, k in enumerate(keys)}, bib


# ---------------------------------------------------------------- inline ----
class InlineParser:
    """Turn a LaTeX fragment into a list of (text, fmt) runs."""

    def __init__(self, cites):
        self.cites = cites

    def parse(self, s: str, fmt=None):
        runs = []
        i = 0
        buf = []

        def flush():
            if buf:
                runs.append(("".join(buf), fmt))
                buf.clear()

        while i < len(s):
            ch = s[i]
            if ch == "\\":
                m = re.match(r"\\([A-Za-z]+)\s*", s[i:])
                if m:
                    cmd = m.group(1)
                    j = i + m.end()
                    if cmd in ("textbf", "emph", "texttt", "textit", "textsc", "textsuperscript",
                               "textsubscript", "mathrm", "text", "mbox"):
                        arg, j2 = self._group(s, j)
                        if arg is None:
                            buf.append(s[i]); i += 1; continue
                        sub = {"textbf": "b", "emph": "i", "textit": "i", "texttt": "tt",
                               "textsc": "sc", "textsuperscript": "sup",
                               "textsubscript": "sub", "mathrm": "i", "text": None,
                               "mbox": None}[cmd]
                        inner_fmt = sub if sub else fmt
                        # nested markup inside \text is rare here
                        flush()
                        runs.extend(self.parse(arg, inner_fmt))
                        i = j2
                        continue
                    if cmd == "cite":
                        arg, j2 = self._group(s, j)
                        if arg is not None:
                            nums = []
                            for k in arg.split(","):
                                k = k.strip()
                                if k in self.cites:
                                    nums.append(self.cites[k])
                            flush()
                            if nums:
                                runs.append((", ".join(f"[{n}]" for n in nums), fmt))
                            i = j2
                            continue
                    if cmd == "ref":
                        arg, j2 = self._group(s, j)
                        if arg is not None:
                            flush()
                            runs.append((LABELS.get(arg, arg), fmt))
                            i = j2
                            continue
                    if cmd in ("input", "label"):
                        arg, j2 = self._group(s, j)
                        i = j2
                        continue
                    if cmd in ("%", "&", "#", "_", "{", "}", "$"):
                        buf.append(cmd); i = j + 0
                        # j already consumed the trailing spaces; rewind to the char
                        i = i
                        continue
                    # unknown command: drop it
                    i = j
                    continue
                # escaped punctuation and spacing commands
                if i + 1 < len(s):
                    nxt = s[i + 1]
                    if nxt in "%&$#_{}":
                        buf.append(nxt); i += 2; continue
                    if nxt in ",; ":
                        buf.append(" "); i += 2; continue
                    if nxt == "!":
                        i += 2; continue
                    if nxt == "\\":
                        buf.append(" "); i += 2; continue
                i += 1
                continue
            if ch == "$":
                j = s.find("$", i + 1)
                if j == -1:
                    buf.append(ch); i += 1; continue
                flush()
                runs.extend(self._math(s[i + 1:j], fmt))
                i = j + 1
                continue
            if ch == "~":
                buf.append(" "); i += 1; continue
            if s.startswith("---", i):
                buf.append("\u2014"); i += 3; continue
            if s.startswith("--", i):
                buf.append("\u2013"); i += 2; continue
            if ch == "`":
                if s.startswith("``", i):
                    buf.append("\u201c"); i += 2; continue
                buf.append("\u2018"); i += 1; continue
            if ch == "'":
                if s.startswith("''", i):
                    buf.append("\u201d"); i += 2; continue
                buf.append("\u2019"); i += 1; continue
            buf.append(ch); i += 1
        flush()
        return [r for r in runs if r[0] != ""]

    @staticmethod
    def _group(s, i):
        while i < len(s) and s[i] in " \t":
            i += 1
        if i >= len(s) or s[i] != "{":
            return None, i
        depth = 0
        for k in range(i, len(s)):
            if s[k] == "{":
                depth += 1
            elif s[k] == "}":
                depth -= 1
                if depth == 0:
                    return s[i + 1:k], k + 1
        return None, i

    def _math(self, m, fmt):
        """Convert simple inline math into runs, mapping _ and ^ to sub/sup."""
        out = []
        # normalise symbols first
        for k, v in SYM.items():
            m = m.replace(k, v)
        m = re.sub(r"\\([A-Za-z]+)", r"\1", m)
        m = m.replace("\\,", " ").replace("\\;", " ").replace("\\!", "")
        m = m.replace("\\ ", " ")
        tok = []
        i = 0
        while i < len(m):
            c = m[i]
            if c in "_^" and i + 1 < len(m):
                kind = "sub" if c == "_" else "sup"
                if m[i + 1] == "{":
                    depth = 0
                    for k in range(i + 1, len(m)):
                        if m[k] == "{":
                            depth += 1
                        elif m[k] == "}":
                            depth -= 1
                            if depth == 0:
                                tok.append((m[i + 2:k], kind)); i = k + 1; break
                    else:
                        i += 1
                else:
                    tok.append((m[i + 1], kind)); i += 2
                continue
            tok.append((c, fmt)); i += 1
        # merge adjacent same-format pieces
        for t, f in tok:
            if out and out[-1][1] == f:
                out[-1] = (out[-1][0] + t, f)
            else:
                out.append((t, f))
        return out


# ------------------------------------------------------------------ body ----
def parse_body(tex: str, bib: str, inline: InlineParser):
    body = tex[tex.index("\\begin{abstract}"):]
    body = body[: body.index("\\begin{thebibliography}")]

    blocks = []

    # abstract + keywords
    abst = re.search(r"\\begin\{abstract\}(.*?)\\end\{abstract\}", body, re.S).group(1).strip()
    blocks.append(("abstract", inline.parse(re.sub(r"\s+", " ", abst))))
    kw = re.search(r"\\begin\{IEEEkeywords\}(.*?)\\end\{IEEEkeywords\}", body, re.S)
    if kw:
        blocks.append(("keywords", inline.parse(re.sub(r"\s+", " ", kw.group(1).strip()))))

    body = body[body.index("\\end{IEEEkeywords}") + len("\\end{IEEEkeywords}"):] \
        if kw else body[body.index("\\end{abstract}") + len("\\end{abstract}"):]

    # remove generated table bodies and figure/table floats (built separately)
    body = re.sub(r"\\begin\{table\*?\}.*?\\end\{table\*?\}", "\n@@TABLE@@\n", body, flags=re.S)
    body = re.sub(r"\\begin\{figure\}.*?\\end\{figure\}", "\n@@FIGURE@@\n", body, flags=re.S)
    body = re.sub(r"\\begin\{equation\}.*?\\end\{equation\}", "\n@@EQUATION@@\n", body, flags=re.S)

    pos = {"@@TABLE@@": 0, "@@FIGURE@@": 0}

    # split into \section / \subsection chunks
    parts = re.split(r"(\\(?:sub)?section\{[^}]*\})", body)
    order = re.finditer(r"\\cite\{([^}]+)\}", body)
    for part in parts:
        part = part.strip()
        if not part:
            continue
        m = re.match(r"\\section\{(.*?)\}", part, re.S)
        if m:
            blocks.append(("h1", inline.parse(re.sub(r"\s+", " ", m.group(1)))))
            rest = part[m.end():]
            if rest.strip():
                blocks.extend(_paras(rest, inline))
            continue
        m = re.match(r"\\subsection\{(.*?)\}", part, re.S)
        if m:
            blocks.append(("h2", inline.parse(re.sub(r"\s+", " ", m.group(1)))))
            rest = part[m.end():]
            if rest.strip():
                blocks.extend(_paras(rest, inline))
            continue
        blocks.extend(_paras(part, inline))

    # Float position markers are kept: the DOCX builder replaces them, in
    # order, with the generated tables, figures and equation.
    return blocks


def _paras(chunk: str, inline: InlineParser):
    """Split a chunk into paragraph / bullet / marker blocks."""
    res = []
    # itemize environments
    while True:
        m = re.search(r"\\begin\{itemize\}(.*?)\\end\{itemize\}", chunk, re.S)
        if not m:
            break
        before, items_src, after = chunk[:m.start()], m.group(1), chunk[m.end():]
        res.extend(_plain(before, inline))
        items = [it.strip() for it in re.split(r"\\item\s", items_src) if it.strip()]
        res.append(("bullets", [inline.parse(re.sub(r"\s+", " ", it)) for it in items]))
        chunk = after
    res.extend(_plain(chunk, inline))
    return res


def _plain(chunk: str, inline: InlineParser):
    out = []
    for raw in re.split(r"\n\s*\n", chunk):
        raw = raw.strip()
        if not raw:
            continue
        if raw in ("@@TABLE@@", "@@FIGURE@@", "@@EQUATION@@"):
            out.append(("p", raw))
            continue
        txt = re.sub(r"\s+", " ", raw)
        runs = inline.parse(txt)
        if runs:
            out.append(("p", runs))
    return out


def main():
    tex = strip_comments(SRC.read_text())
    MACROS = load_macros("../repo/paper/results_macros.tex")
    tex = expand_macros(tex, MACROS).replace("{,}", ",")
    cites, bib = build_citation_map(tex)
    inline = InlineParser(cites)

    title_raw = re.search(r"\\title\{(.*?)\}\s*\n", tex, re.S).group(1)
    title = re.sub(r"\s+", " ", title_raw.replace("\\\\", " ")).strip()

    abstract = re.search(r"\\begin\{abstract\}(.*?)\\end\{abstract\}", tex, re.S).group(1)
    abstract = re.sub(r"\s+", " ", abstract).strip()
    keywords = re.search(r"\\begin\{IEEEkeywords\}(.*?)\\end\{IEEEkeywords\}", tex, re.S)
    keywords = re.sub(r"\s+", " ", keywords.group(1)).strip() if keywords else ""

    # references
    refs = []
    for entry in re.split(r"\\bibitem\{", bib)[1:]:
        key = entry[: entry.index("}")]
        text = entry[entry.index("}") + 1:].strip()
        text = re.sub(r"\s+", " ", text)
        refs.append({"key": key, "runs": inline.parse(text)})

    # narrative blocks, with float markers expanded in order
    body_tex = tex[tex.index("\\begin{abstract}"): tex.index("\\begin{thebibliography}")]
    n_tables = len(re.findall(r"\\begin\{table\*?\}", body_tex))
    n_figs = len(re.findall(r"\\begin\{figure\}", body_tex))
    n_eqs = len(re.findall(r"\\begin\{equation\}", body_tex))

    blocks = parse_body(tex, bib, inline)

    ir = {
        "title": title,
        "authors": [
            {"name": "Sushant Poudel", "email": "sushant.poudel2028@gmail.com"},
            {"name": "Rakhee Pandey", "email": "rakheepandey5712@gmail.com"},
            {"name": "Aashika Pandey", "email": "aashika100pandey@gmail.com"},
        ],
        "affiliation": "Dept. of Computer Science and Engineering, Nepal Engineering College, Bhaktapur, Nepal",
        "abstract": inline.parse(abstract),
        "keywords": inline.parse(keywords),
        "blocks": blocks,
        "references": refs,
        "counts": {"tables": n_tables, "figures": n_figs, "equations": n_eqs},
    }
    Path("paper_ir.json").write_text(json.dumps(ir, indent=1, ensure_ascii=False))

    left = sorted(set(re.findall(r"\\\\([A-Za-z]+)", " ".join(
        "".join(x for x, _ in runs)
        for runs in [ir["abstract"], ir["keywords"]]
        + [v for k, v in ir["blocks"] if k in ("h1", "h2")]
        + [v for k, v in ir["blocks"] if k == "p" and not isinstance(v, str)]
        + [it for k, v in ir["blocks"] if k == "bullets" for it in v]))))
    print("unexpanded macros:", left if left else "none")

    print(f"title      : {title[:80]}")
    print(f"abstract   : {len(abstract)} chars")
    print(f"keywords   : {keywords[:70]}")
    print(f"references : {len(refs)}")
    print(f"blocks     : {len(blocks)}  ({n_tables} tables, {n_figs} figures, {n_eqs} equation)")
    from collections import Counter
    print("block kinds:", dict(Counter(k for k, _ in blocks)))


if __name__ == "__main__":
    main()
