#!/usr/bin/env python3
"""
Emit LaTeX macros and table fragments from metrics.json so that the manuscript
prose can be written once and the numbers substituted mechanically.

Usage:
    python src/make_macros.py --metrics results/metrics.json --outdir paper
    python src/make_macros.py --dummy --outdir paper      # placeholder build
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

SUF = {"naive": "Naive", "zeroshot": "Zero", "cot": "Cot"}
CONDS = ["naive", "zeroshot", "cot"]

PRETTY = {
    "instruction_override": "Instruction override",
    "authority_framing": "Authority framing",
    "context_delimiter_spoof": "Context-delimiter spoof",
    "encoding_obfuscation": "Encoding obfuscation",
    "payload_splitting": "Payload splitting",
    "false_policy_assertion": "False policy assertion",
    "urgency_pressure": "Urgency pressure",
    "indirect_tool_output": "Indirect tool output",
}


def num(v, nd=1):
    if v is None:
        return "---"
    if isinstance(v, float):
        return f"{v:.{nd}f}"
    return str(v)


def build(m):
    L = []
    A = L.append

    A("% Auto-generated by make_macros.py -- do not edit by hand.")
    A("\\newcommand{\\NScen}{%s}" % m["cot"]["n_total"])
    A("\\newcommand{\\NTrials}{%s{,}%03d}" % ((3 * m["cot"]["n_total"]) // 1000,
                                               (3 * m["cot"]["n_total"]) % 1000))
    A("\\newcommand{\\TRuleA}{%s}" % m["cot"]["per_rule"]["A"]["n"])
    A("\\newcommand{\\VRAMPeak}{3.95}")
    A("")

    for c in CONDS:
        s = SUF[c]
        d = m[c]
        A("%% ---- %s ----" % c)
        A("\\newcommand{\\Parsed%s}{%s}" % (s, d["n_parsed"]))
        A("\\newcommand{\\Parse%s}{%s}" % (s, num(d["parse_failure_rate"])))
        A("\\newcommand{\\Amb%s}{%s}" % (s, num(d["ambiguous_rate"])))
        if "multi_verdict_rate" in d:
            A("\\newcommand{\\Multi%s}{%s}" % (s, num(d["multi_verdict_rate"])))
        A("\\newcommand{\\Acc%s}{%s}" % (s, num(d["decision_accuracy"])))
        lo, hi = d["decision_accuracy_ci"]
        A("\\newcommand{\\AccCI%s}{%s--%s}" % (s, num(lo), num(hi)))
        A("\\newcommand{\\RuleAttr%s}{%s}" % (s, num(d["rule_attribution_accuracy"])))
        if d.get("self_consistency_n"):
            A("\\newcommand{\\Consist%s}{%s}" % (s, num(d["self_consistency"])))
        A("\\newcommand{\\Unsafe%s}{%s}" % (s, d["unsafe_accept"]))
        A("\\newcommand{\\UnsafeRate%s}{%s}" % (s, num(d["unsafe_accept_rate"])))
        A("\\newcommand{\\UnsafeDeny%s}{%s}" % (s, d["unsafe_accept_on_deny"]))
        A("\\newcommand{\\UnsafeFlag%s}{%s}" % (s, d["unsafe_accept_on_flag"]))
        A("\\newcommand{\\LatMed%s}{%s}" % (s, num(d["latency_median_s"], 2)))
        A("\\newcommand{\\LatP%s}{%s}" % (s, num(d["latency_p95_s"], 2)))
        A("\\newcommand{\\TokS%s}{%s}" % (s, num(d["tok_per_s_mean"], 1)))
        for r in "ABC":
            A("\\newcommand{\\Acc%s%s}{%s}" % (r, s, num(d["per_rule"][r]["decision_accuracy"])))
            A("\\newcommand{\\RuleAttr%s%s}{%s}" % (r, s, num(d["per_rule"][r]["rule_attribution_accuracy"])))
        for t, key in (("standard", "Std"), ("adversarial", "Adv"),
                       ("compound", "Cmp"), ("edge", "Edge")):
            A("\\newcommand{\\%sAcc%s}{%s}" % (key, s, num(d["per_tag"][t]["decision_accuracy"])))
        A("")

    A("% ---- corpus table ----")
    A("\\newcommand{\\CorpusA}{%s}" % m["cot"]["per_rule"]["A"]["n"])
    A("\\newcommand{\\CorpusB}{%s}" % m["cot"]["per_rule"]["B"]["n"])
    A("\\newcommand{\\CorpusC}{%s}" % m["cot"]["per_rule"]["C"]["n"])

    # ---- run-to-run replication agreement ----
    rep = m.get("_replication")
    if rep:
        A("")
        A("% ---- replication agreement ----")
        A("\\newcommand{\\ReplNaive}{%s}" % num(rep["naive"]["decision_agreement"]))
        A("\\newcommand{\\ReplZero}{%s}" % num(rep["zeroshot"]["decision_agreement"]))
        A("\\newcommand{\\ReplCot}{%s}" % num(rep["cot"]["decision_agreement"]))
        A("\\newcommand{\\ReplRuleCot}{%s}" % num(rep["cot"]["rule_agreement"]))
        A("\\newcommand{\\ReplN}{%s}" % rep["cot"]["n"])

    # ---- ablation arm: structured CoT with a declared action vector ----
    if "cot_av" in m:
        av, base = m["cot_av"], m["cot"]
        A("")
        A("% ---- ablation: declared action vector ----")
        A("\\newcommand{\\AvAcc}{%s}" % num(av["decision_accuracy"]))
        A("\\newcommand{\\AvAccA}{%s}" % num(av["per_rule"]["A"]["decision_accuracy"]))
        A("\\newcommand{\\AvAccB}{%s}" % num(av["per_rule"]["B"]["decision_accuracy"]))
        A("\\newcommand{\\AvAccC}{%s}" % num(av["per_rule"]["C"]["decision_accuracy"]))
        A("\\newcommand{\\AvRuleAttr}{%s}" % num(av["rule_attribution_accuracy"]))
        A("\\newcommand{\\AvRuleAttrA}{%s}" % num(av["per_rule"]["A"]["rule_attribution_accuracy"]))
        A("\\newcommand{\\AvRuleAttrB}{%s}" % num(av["per_rule"]["B"]["rule_attribution_accuracy"]))
        A("\\newcommand{\\AvRuleAttrC}{%s}" % num(av["per_rule"]["C"]["rule_attribution_accuracy"]))
        A("\\newcommand{\\AvConsist}{%s}" % num(av.get("self_consistency", 0)))
        A("\\newcommand{\\AvUnsafe}{%s}" % av["unsafe_accept"])
        A("\\newcommand{\\AvUnsafeDeny}{%s}" % av["unsafe_accept_on_deny"])
        A("\\newcommand{\\AvUnsafeRate}{%s}" % num(av["unsafe_accept_rate"]))
        A("\\newcommand{\\AvAdvAcc}{%s}" % num(av["per_tag"]["adversarial"]["decision_accuracy"]))
        A("\\newcommand{\\CotMisAC}{%s}" % base["misattribution"].get("A->C", 0))
        A("\\newcommand{\\CotMisBC}{%s}" % base["misattribution"].get("B->C", 0))
        A("\\newcommand{\\AvMisAC}{%s}" % av["misattribution"].get("A->C", 0))
        A("\\newcommand{\\AvMisBC}{%s}" % av["misattribution"].get("B->C", 0))
    return "\n".join(L) + "\n"


def build_adv_rows(m):
    """Full table *body* (data rows through \bottomrule).

    The trailing rules live inside this fragment on purpose: a rule command
    that follows an \\input whose file ends in \\\\ cannot resolve its
    lookahead across the file boundary, so the fragment must be self-contained.
    """
    techs = sorted({t for c in CONDS for t in m[c]["per_technique"]})
    rows = []
    for t in techs:
        n = m["cot"]["per_technique"][t]["n"]
        cells = [num(m[c]["per_technique"].get(t, {}).get("accuracy")) for c in CONDS]
        rows.append(f"{PRETTY.get(t, t)} & {n} & " + " & ".join(cells) + r" \\")
    rows.append(r"\midrule")
    for label, key in (("All adversarial", "adversarial"), ("Standard only", "standard"),
                       ("Compound", "compound"), ("Boundary", "edge")):
        n = m["cot"]["per_tag"][key]["n"]
        cells = [num(m[c]["per_tag"][key]["decision_accuracy"]) for c in CONDS]
        rows.append(r"\textbf{%s} & %s & %s \\" % (label, n, " & ".join(cells)))
    rows.append(r"\bottomrule")
    return "\n".join(rows) + "\n"


DUMMY = {
    c: {
        "n_total": 600, "n_parsed": 600 if c != "naive" else 520,
        "parse_failure_rate": 0.0 if c != "naive" else 13.3,
        "ambiguous_rate": 0.0 if c != "naive" else 21.0,
        "multi_verdict_rate": 0.0 if c != "naive" else 24.0,
        "decision_accuracy": 41.0, "decision_accuracy_ci": [37.0, 45.0],
        "rule_attribution_accuracy": 55.0, "unsafe_accept": 40,
        "unsafe_accept_rate": 6.7, "unsafe_accept_on_deny": 30, "unsafe_accept_on_flag": 10,
        "latency_median_s": 2.0, "latency_p95_s": 5.0, "tok_per_s_mean": 60.0,
        "per_rule": {r: {"n": 200, "decision_accuracy": 41.0,
                         "rule_attribution_accuracy": 55.0} for r in "ABC"},
        "per_tag": {t: {"n": 100, "decision_accuracy": 41.0}
                    for t in ("standard", "adversarial", "compound", "edge")},
        "per_technique": {t: {"n": 19, "accuracy": 41.0} for t in PRETTY},
        "misattribution": {"A->C": 30, "B->C": 10},
    }
    for c in CONDS
}
DUMMY["cot_av"] = {
    **DUMMY["cot"],
    "decision_accuracy": 55.0,
    "rule_attribution_accuracy": 68.0,
    "unsafe_accept": 22,
    "unsafe_accept_on_deny": 15,
    "unsafe_accept_rate": 3.7,
    "per_rule": {r: {**DUMMY["cot"]["per_rule"][r],
                     "decision_accuracy": 55.0,
                     "rule_attribution_accuracy": 68.0} for r in "ABC"},
    "per_tag": {t: {**DUMMY["cot"]["per_tag"][t], "decision_accuracy": 55.0}
                for t in ("standard", "adversarial", "compound", "edge")},
    "misattribution": {"A->C": 8},
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--metrics", default="results/metrics.json")
    ap.add_argument("--outdir", default="paper")
    ap.add_argument("--dummy", action="store_true")
    args = ap.parse_args()

    m = DUMMY if args.dummy else json.loads(Path(args.metrics).read_text())
    out = Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "results_macros.tex").write_text(build(m))
    (out / "adv_table.tex").write_text(build_adv_rows(m))
    print(f"wrote {out/'results_macros.tex'} and {out/'adv_table.tex'}"
          + ("  [DUMMY]" if args.dummy else ""))


if __name__ == "__main__":
    main()
